name: ivf_project
description: "A new Flutter project."

version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/app_icon.png
    - assets/babsae_gansa.png
    - assets/babsae_student.png
    - assets/kakao_symbol.png
  fonts:
    - family: SEOLLEIM
      fonts:
        - asset: assets/fonts/SEOLLEIMcool.ttf
  uses-material-design: true
